CREATE TABLE nasc
(
  NUMERODN BIGINT
, CODINST VARCHAR(30)
, ORIGEM DOUBLE PRECISION
, NUMERODV DOUBLE PRECISION
, PREFIXODN DOUBLE PRECISION
, CODESTAB VARCHAR(20)
, CODMUNNASC BIGINT
, LOCNASC BIGINT
, def_loc_nasc VARCHAR(19)
, IDADEMAE BIGINT
, ESTCIVMAE BIGINT
, def_est_civil VARCHAR(50)
, ESCMAE BIGINT
, def_escol_mae VARCHAR(15)
, CODOCUPMAE DOUBLE PRECISION
, QTDFILVIVO BIGINT
, QTDFILMORT BIGINT
, CODMUNRES BIGINT
, GESTACAO BIGINT
, def_gestacao VARCHAR(19)
, GRAVIDEZ BIGINT
, def_gravidez VARCHAR(14)
, PARTO BIGINT
, def_parto VARCHAR(8)
, CONSULTAS BIGINT
, def_consultas VARCHAR(8)
, DTNASC BIGINT
, data_nasc TIMESTAMP
, ano_nasc BIGINT
, dia_semana_nasc VARCHAR(4)
, HORANASC VARCHAR(10)
, SEXO BIGINT
, def_sexo VARCHAR(9)
, APGAR1 VARCHAR(15)
, APGAR5 VARCHAR(15)
, RACACOR BIGINT
, def_raca_cor VARCHAR(8)
, PESO BIGINT
, IDANOMAL BIGINT
, def_anomalia VARCHAR(8)
, DTCADASTRO DOUBLE PRECISION
, CODANOMAL VARCHAR(20)
, NUMEROLOTE DOUBLE PRECISION
, VERSAOSIST VARCHAR(20)
, DTRECEBIM DOUBLE PRECISION
, DIFDATA DOUBLE PRECISION
, DTRECORIGA DOUBLE PRECISION
, NATURALMAE DOUBLE PRECISION
, CODMUNNATU DOUBLE PRECISION
, CODUFNATU DOUBLE PRECISION
, ESCMAE2010 DOUBLE PRECISION
, SERIESCMAE DOUBLE PRECISION
, DTNASCMAE DOUBLE PRECISION
, RACACORMAE DOUBLE PRECISION
, QTDGESTANT DOUBLE PRECISION
, QTDPARTNOR DOUBLE PRECISION
, QTDPARTCES DOUBLE PRECISION
, IDADEPAI DOUBLE PRECISION
, DTULTMENST DOUBLE PRECISION
, SEMAGESTAC DOUBLE PRECISION
, TPMETESTIM DOUBLE PRECISION
, CONSPRENAT DOUBLE PRECISION
, MESPRENAT DOUBLE PRECISION
, TPAPRESENT DOUBLE PRECISION
, STTRABPART DOUBLE PRECISION
, STCESPARTO DOUBLE PRECISION
, TPNASCASSI DOUBLE PRECISION
, TPFUNCRESP DOUBLE PRECISION
, TPDOCRESP DOUBLE PRECISION
, DTDECLARAC DOUBLE PRECISION
, ESCMAEAGR1 DOUBLE PRECISION
, STDNEPIDEM DOUBLE PRECISION
, STDNNOVA DOUBLE PRECISION
, CODPAISRES DOUBLE PRECISION
, TPROBSON DOUBLE PRECISION
, PARIDADE DOUBLE PRECISION
, KOTELCHUCK DOUBLE PRECISION
, nasc_MUNNOME VARCHAR(50)
, nasc_MUNNOMEX VARCHAR(50)
, nasc_AMAZONIA VARCHAR(1)
, nasc_FRONTEIRA VARCHAR(1)
, nasc_CAPITAL VARCHAR(1)
, nasc_MSAUDCOD BIGINT
, nasc_RSAUDCOD BIGINT
, nasc_CSAUDCOD BIGINT
, nasc_LATITUDE BIGINT
, nasc_LONGITUDE BIGINT
, nasc_ALTITUDE BIGINT
, nasc_AREA BIGINT
, nasc_codigo_adotado BIGINT
, res_MUNNOME VARCHAR(80)
, res_MUNNOMEX VARCHAR(80)
, res_AMAZONIA VARCHAR(1)
, res_FRONTEIRA VARCHAR(1)
, res_CAPITAL VARCHAR(1)
, res_MSAUDCOD BIGINT
, res_RSAUDCOD BIGINT
, res_CSAUDCOD BIGINT
, res_LATITUDE BIGINT
, res_LONGITUDE BIGINT
, res_ALTITUDE BIGINT
, res_AREA BIGINT
, res_codigo_adotado BIGINT
, nasc_SIGLA_UF VARCHAR(2)
, nasc_CODIGO_UF BIGINT
, nasc_NOME_UF VARCHAR(20)
, res_SIGLA_UF VARCHAR(2)
, res_CODIGO_UF BIGINT
, res_NOME_UF VARCHAR(20)
, nasc_REGIAO VARCHAR(15)
, res_REGIAO VARCHAR(15)
, codanomal_capitulo VARCHAR(300)
, codanomal_grupo VARCHAR(300)
, codanomal_categoria VARCHAR(300)
, codanomal_subcategoria VARCHAR(300)
, nasc_coordenadas VARCHAR(19)
, res_coordenadas VARCHAR(19)
, parto_prematuro BIGINT
, def_parto_prematuro VARCHAR(17)
)
;

CREATE INDEX ON NASC(ESCMAE);
CREATE INDEX ON NASC(IDADEMAE);
CREATE INDEX ON NASC(RACACORMAE);
CREATE INDEX ON NASC(ESTCIVMAE);
CREATE INDEX ON NASC(DTNASCMAE);
CREATE INDEX ON NASC(CODOCUPMAE);
CREATE INDEX ON NASC(CODMUNRES);
CREATE INDEX ON NASC(CODMUNNATU);
CREATE INDEX ON NASC(CODUFNATU);
CREATE INDEX ON NASC(NATURALMAE);
CREATE INDEX ON NASC(DTULTMENST);
CREATE INDEX ON NASC(QTDGESTANT);
CREATE INDEX ON NASC(QTDPARTNOR);
CREATE INDEX ON NASC(QTDPARTCES);
CREATE INDEX ON NASC(QTDFILVIVO);
CREATE INDEX ON NASC(QTDFILMORT);
CREATE INDEX ON NASC(GRAVIDEZ);
CREATE INDEX ON NASC(GESTACAO);
CREATE INDEX ON NASC(CONSULTAS);
CREATE INDEX ON NASC(SEMAGESTAC);
CREATE INDEX ON NASC(TPMETESTIM);
CREATE INDEX ON NASC(CONSPRENAT);
CREATE INDEX ON NASC(MESPRENAT);
CREATE INDEX ON NASC(APGAR1);
CREATE INDEX ON NASC(APGAR5);
CREATE INDEX ON NASC(RACACOR);
CREATE INDEX ON NASC(PESO);
CREATE INDEX ON NASC(data_nasc);
CREATE INDEX ON NASC(dia_semana_nasc);
CREATE INDEX ON NASC(HORANASC);
CREATE INDEX ON NASC(SEXO);
CREATE INDEX ON NASC(KOTELCHUCK);
CREATE INDEX ON NASC(TPROBSON);
CREATE INDEX ON NASC(parto_prematuro);
CREATE INDEX ON NASC(PARTO);
CREATE INDEX ON NASC(TPNASCASSI);
CREATE INDEX ON NASC(STCESPARTO);
CREATE INDEX ON NASC(TPAPRESENT);
CREATE INDEX ON NASC(STTRABPART);
CREATE INDEX ON NASC(CODESTAB);
CREATE INDEX ON NASC(IDADEPAI);
CREATE INDEX ON NASC(LOCNASC);
CREATE INDEX ON NASC(nasc_MUNNOME);
CREATE INDEX ON NASC(nasc_AMAZONIA);
CREATE INDEX ON NASC(nasc_FRONTEIRA);
CREATE INDEX ON NASC(nasc_CAPITAL);
CREATE INDEX ON NASC(nasc_MSAUDCOD);
CREATE INDEX ON NASC(nasc_RSAUDCOD);
CREATE INDEX ON NASC(nasc_CSAUDCOD);
CREATE INDEX ON NASC(nasc_ALTITUDE);
CREATE INDEX ON NASC(nasc_AREA);
CREATE INDEX ON NASC(nasc_codigo_adotado);
CREATE INDEX ON NASC(nasc_SIGLA_UF);
CREATE INDEX ON NASC(nasc_REGIAO);
CREATE INDEX ON NASC(nasc_coordenadas);
CREATE INDEX ON NASC(CODMUNNASC);
CREATE INDEX ON NASC(res_MUNNOME);
CREATE INDEX ON NASC(res_AMAZONIA);
CREATE INDEX ON NASC(res_FRONTEIRA);
CREATE INDEX ON NASC(res_CAPITAL);
CREATE INDEX ON NASC(res_MSAUDCOD);
CREATE INDEX ON NASC(res_RSAUDCOD);
CREATE INDEX ON NASC(res_CSAUDCOD);
CREATE INDEX ON NASC(res_ALTITUDE);
CREATE INDEX ON NASC(res_AREA);
CREATE INDEX ON NASC(res_codigo_adotado);
CREATE INDEX ON NASC(res_SIGLA_UF);
CREATE INDEX ON NASC(res_REGIAO);
CREATE INDEX ON NASC(res_coordenadas);
CREATE INDEX ON NASC(CODPAISRES);
CREATE INDEX ON NASC(IDANOMAL);
CREATE INDEX ON NASC(codanomal_capitulo);
CREATE INDEX ON NASC(codanomal_grupo);
CREATE INDEX ON NASC(codanomal_categoria);
CREATE INDEX ON NASC(codanomal_subcategoria);
CREATE INDEX ON NASC(CODANOMAL);
